config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  resources :users, only: [:show]
  resources :posts
  resources :user_contracts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {
    scope: :post_id,
    message: "は同じ投稿に2回以上いいねはできません"
  }
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :subscription, optional: true
  has_many :likes, dependent: :destroy

  validates :content, presence: true

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  has_many :posts
  has_many :user_contracts
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :user_contracts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def self.guest
    find_or_create_by(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end
end

app/models/user_contract.rb
class UserContract < ApplicationRecord
  belongs_to :user
  belongs_to :subscription
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: :index
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  #登録時のnameの許可
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  #ログイン後の飛び先指定
  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @posts = Post.all.order(id: :desc).limit(3)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(id: :asc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @subscriptions = Subscription.all
  end

  def create
    @post = current_user.posts.new(content: post_params[:content], user_id: post_params[:user_id], subscription_id: post_params[:subscription_id])

    if @post.save
      redirect_to @post, notice: "投稿が完了しました"
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update!(post_params)
    redirect_to posts_url, notice: "更新しました"
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy!
    redirect_to posts_url, notice: "削除しました"
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :subscription_id)
  end
end

app/controllers/user_contracts_controller.rb
class UserContractsController < ApplicationController
  def index
    @user_contracts = current_user.user_contracts.all.order(contract_date: :asc )
  end

  def show
  end

  def new
    @user_contract = UserContract.new
    @subscriptions = Subscription.all
  end

  def create
    @user_contract = UserContract.new(contract_date: user_contract_params[:contract_date], cancellation_date: user_contract_params[:cancellation_date], user_id: current_user.id, subscription_id: user_contract_params[:subscription_id])
    
    if @user_contract.save!
      redirect_to user_contracts_path, notice: "登録が完了しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_contract_params
    params.require(:user_contract).permit(:contract_date, :cancellation_date, :user_id, :subscription_id)
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
       redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません'
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

  def check_guest
    if resource.email == 'guest@example.com'
       redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/views/homes/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>submanetop</title>
</head>
<body>
  <section class="mainvisual">
    <div class="catchcopy-title">
      <h1>サブマネなら<br>使っているサブスクを<br>カンタン管理</h1>
      <div class="catchcopy-addition">
      <% if user_signed_in? %>
        <div class="form-group">
          <p>\ お気に入りのサブスクを共有しよう！ /</p>
          <%= link_to 'みんなの口コミはこちら', posts_path, class: "btn btn--green btn--radius" %>
        </div>
      <% else %>
          <p>\ まずはお試し！ /</p>
          <%= link_to "無料会員登録", new_user_registration_path, class: "btn btn--green btn--radius" %>
      <% end %>
      </div>
    </div>
    <div class="subscription-image">
      <img src="/assets/subscription.jpg" alt="top画">
    </div>
  </section>
  <main>
  <section class="questions">
    <div class="content-wrapper">
      <div class="contents">
        <h2>サブスクリプションサービスを利用していて、こんな経験ありませんか？<br>サブマネはこんなお悩みをサクッと解決！</h2>
          <div class="content">
            <ul class="content-list">
              <li><i class="fas fa-check"></i> どのサービスを契約しているか覚えてない</li>
              <li><i class="fas fa-check"></i> 少額だし、いつか使うかもと放置</li>
              <li><i class="fas fa-check"></i> 無料期間があるからとりあえず契約してそのまま</li>
            </ul>
          </div>
      </div>
    </div>
  </section>
  <section class="posts">
    <div class="content-wrapper">
      <div class="contents">
        <h3>最新の口コミ投稿</h3>

        <p>全ての投稿内容を見るためには無料会員登録が必要です。</p>
      </div>
    </div>
    <% @posts.each do |post| %>
    <div class="card border-primary mb-3" style="max-width: 60rem;">
      <div class="card-header border-primary"><%= post.user.name %>さん</div>
      <div class="card-body">
        <p class="card-text"><%= post.content %></p>
      </div>
      <div class="card-footer bg-transparent border-primary"><%= post.created_at %></div>
    </div>
    <% end %>
  </section>
</body>
</html>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="wrapper">
    <p><small>Copyright &copy; tk_e1950 All Rights Reserved</small></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand navbar-dark" style="background-color: #55c500">
    <%= link_to "サブマネ ~Subscription Management~", root_path, class: 'navbar-brand' %>
    <div id="Navber">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to '投稿一覧', posts_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'マイページ', user_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
      <% else %>
          <li class="nav-item active">
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to "無料会員登録", new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubsManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="base-container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
  </html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>口コミ編集</h1>
投稿日: <%= @post.created_at%>
<%= form_with model: @post, local: true do |form| %>
  <div class="form-group">
    <%= form.label :content, "内容" %>
    <%= form.text_area :content, rows: 5, class: "form-control", required: true %>
  </div>
  <div>
    <%= form.submit "更新する", class: "btn btn-outline-primary" %>
<% end %>

app/views/posts/index.html.erb
<h1 class="text-center">みんなの口コミ</h1>
<%= link_to "新規投稿", new_post_path, class: 'btn btn-primary' %>
<table class="table table-bordered table-striped mt-4">
  <thead class="table-primary">
    <tr>
      <th scope="col">投稿日</th>
      <th scope="col">サブスクリプション名</th>
      <th scope="col">投稿内容</th>
      <th scope="col">投稿者</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= post.created_at %>
        </td>
        <td>
          <%= post.subscription.service_name %>       
        </td>
        <td>
          <%= link_to post.content, post %>
        </td>
        <td>
          <%= post.user.name %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>口コミの新規投稿</h1>
  <%= form_with model: @post, local: true do |form| %>
    <%= form.collection_select(:subscription_id, @subscriptions, :id, :service_name, {prompt: "利用しているサブスクを選択"} ) %>
    <%= form.label :content, "口コミ入力欄" %>
    <%= form.text_area :content, rows: 5, class: "form-control", required: true %>
    <%= form.submit "投稿する", class: "btn btn-outline-primary" %>
  <% end %>

app/views/posts/show.html.erb
<h1 class="text-center">口コミ詳細</h1>

<p>サブスク名：<%= @post.subscription.service_name %></p>
<p>内容 <%= @post.content %></p>
<p>投稿日時 <%= @post.created_at %></p>
<% if @post.user_id == current_user.id %>
  <%= link_to "編集", edit_post_path %>
  <%= link_to "削除", @post, method: :delete, data: { confirm: "削除しますか？"}  %>
<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/user_contracts/create.html.erb
<h1>UserContracts#create</h1>
<p>Find me in app/views/user_contracts/create.html.erb</p>

app/views/user_contracts/destroy.html.erb
<h1>UserContracts#destroy</h1>
<p>Find me in app/views/user_contracts/destroy.html.erb</p>

app/views/user_contracts/edit.html.erb
<h1>UserContracts#edit</h1>
<p>Find me in app/views/user_contracts/edit.html.erb</p>

app/views/user_contracts/index.html.erb
<h1 class="text-center">契約サブスク一覧</h1>
<%= link_to "サブスク情報登録", new_user_contract_path, class: 'btn btn-primary' %>
<table class="table table-bordered table-striped mt-4">
  <thead class="table-primary">
    <tr>
      <th scope="col">契約日</th>
      <th scope="col">サブスクリプション名</th>
      <th scope="col">ジャンル</th>
      <th scope="col">契約単価（月）</th>
      <th scope="col">契約単価（年）</th>
    </tr>
  </thead>
  <tbody>
    <% @user_contracts.each do |user_contract| %>
      <tr>
        <td>
          <%= user_contract.contract_date %>
        </td>
        <td>
          <%= user_contract.subscription.service_name %>
          </td>
        <td>
          <%= user_contract.subscription.genre %>       
        </td>
        <td>
          <%= user_contract.subscription.monthly_fee %>
        </td>
        <td>
          <%= user_contract.subscription.annual_fee %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user_contracts/new.html.erb
<h1>サブスク情報登録</h1>
  <%= form_with model: @user_contract, local: true do |form| %>
    <%= form.collection_select(:subscription_id, @subscriptions, :id, :service_name, {prompt: "登録するサブスクを選択"} ) %>
    <%= form.label :contract_date, "利用開始日:", class: 'control-label' %>
    <%= form.date_field :contract_date, class: 'from-control' %>
    <%= form.submit "登録する", class: "btn btn-outline-primary" %>
  <% end %>

app/views/user_contracts/show.html.erb
<h1>UserContracts#show</h1>
<p>Find me in app/views/user_contracts/show.html.erb</p>

app/views/user_contracts/update.html.erb
<h1>UserContracts#update</h1>
<p>Find me in app/views/user_contracts/update.html.erb</p>

app/views/users/show.html.erb
<h1><%= @user.name %> さんのマイページ</h1>

  <div class="nav-item active">
    <%= link_to 'アカウント編集', edit_user_registration_path, class: 'nav-link' %>     
  </div>

  <%= link_to "サブスク管理", user_contracts_path, class: 'btn btn-primary' %>
<br>
<h2>このページで出来るようにすること</h2>
<p>契約情報の一覧表示/契約日・サービス名・料金</p>
<p>新しく契約情報を登録することができる</p>
<p>自分の投稿一覧が見れる・投稿ページへ遷移できる</p>


<h2>あとで追加すること</h2>
<p>契約情報を編集することができる（解約日を入れられる）</p>
<p>課金の総額がサービス単位で分かったり、総額の履歴が分かったりする</p>
<p></p>